server:
   port: 8081
   
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbtm001?useSSL=false
    username: root
    password: admin123
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate: 
      ddl-auto: none
  
